# Site settings
title: CogStat - Analyze your data more efficiently
email: krajcsi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  CogStat is an easy to use statistical analysis software.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"
